'use strict';
const V13_READINGS=[
 {id:'r1',minDay:1,title:'Horaires de cours',text:'Le cours de français commence à neuf heures le lundi et le mercredi. Il se termine à dix heures trente. Les étudiants doivent apporter leur cahier et un stylo. Vendredi, il n’y a pas de cours.',qs:[['Quels jours y a-t-il cours ?',['Lundi et mercredi','Mardi et vendredi','Tous les jours'],0],['À quelle heure finit le cours ?',['10 h 30','9 h','11 h 30'],0],['Que faut-il apporter ?',['Un cahier et un stylo','Un ordinateur obligatoire','Un dictionnaire uniquement'],0]]},
 {id:'r2',minDay:1,title:'Petit logement',text:'Julie habite dans un petit appartement près du centre-ville. Il y a une chambre, une cuisine et un salon. Elle aime son quartier parce qu’il est calme et qu’il y a un supermarché à cinq minutes.',qs:[['Où habite Julie ?',['Près du centre-ville','À la campagne','Dans un hôtel'],0],['Pourquoi aime-t-elle son quartier ?',['Il est calme','Il est très loin','Il n’y a aucun magasin'],0],['Quel commerce est proche ?',['Un supermarché','Une gare','Une pharmacie uniquement'],0]]},
 {id:'r3',minDay:1,title:'Message de rendez-vous',text:'Bonjour Paul, notre rendez-vous de mardi à 14 h est déplacé à mercredi à 16 h. Nous nous retrouverons devant la bibliothèque. Si tu n’es pas disponible, appelle-moi avant ce soir.',qs:[['Quel jour est le nouveau rendez-vous ?',['Mercredi','Mardi','Vendredi'],0],['À quelle heure ?',['16 h','14 h','18 h'],0],['Où se retrouvent-ils ?',['Devant la bibliothèque','À la gare','Au restaurant'],0]]},
 {id:'r4',minDay:5,title:'Médiathèque',text:'La médiathèque change ses horaires à partir du 1er septembre. Elle ouvrira à 9 h du mardi au samedi. Le mercredi, elle restera ouverte jusqu’à 21 h pour permettre aux étudiants de travailler plus longtemps. Le samedi, elle fermera à 17 h. Les usagers peuvent aussi réserver des documents en ligne et les récupérer à l’accueil.',qs:[['Quel jour peut-on rester jusqu’à 21 h ?',['Mercredi','Vendredi','Samedi'],0],['Que peut-on faire en ligne ?',['Réserver des documents','Passer un examen','Changer les horaires'],0],['Pourquoi ferme-t-elle plus tard le mercredi ?',['Pour les étudiants','Pour les touristes','Pour les employés'],0]]},
 {id:'r5',minDay:8,title:'Transport partagé',text:'Dans plusieurs villes françaises, les services de vélo partagé attirent de nouveaux utilisateurs. Ils apprécient surtout la liberté de prendre un vélo pour un trajet court sans devoir en acheter un. Cependant, certains usagers regrettent le manque de vélos disponibles le matin près des gares.',qs:[['Quel avantage est mentionné ?',['Pas besoin d’acheter un vélo','Les vélos sont gratuits','Les trajets sont toujours longs'],0],['Quel problème est cité ?',['Le manque de vélos le matin','Le prix du train','La fermeture des gares'],0],['Où apparaît-il surtout ?',['Près des gares','Dans les écoles','Dans les restaurants'],0]]},
 {id:'r6',minDay:12,title:'Télétravail',text:'Depuis deux ans, une petite entreprise autorise ses employés à télétravailler deux jours par semaine. La direction constate que la plupart sont satisfaits et gagnent du temps sur les transports. Elle demande cependant aux équipes de venir au bureau les mêmes jours afin de conserver des moments de collaboration.',qs:[['Combien de jours peut-on télétravailler ?',['Deux','Trois','Cinq'],0],['Quel bénéfice est cité ?',['Gagner du temps de transport','Travailler moins','Être payé davantage'],0],['Pourquoi venir les mêmes jours ?',['Pour collaborer','Pour déjeuner','Pour voyager'],0]]},
 {id:'r7',minDay:19,title:'Semaine de quatre jours',text:'Une entreprise de Nantes teste la semaine de quatre jours sans réduire les salaires. Les salariés travaillent plus longtemps du lundi au jeudi et ont leur vendredi libre. Plusieurs disent être moins stressés, même si certains trouvent les journées plus fatigantes.',qs:[['Quel avantage est cité ?',['Moins de stress','Plus de salaire','Moins de travail chaque jour'],0],['Quelle nuance apparaît ?',['Les journées sont parfois plus fatigantes','Le vendredi est travaillé','Les salaires baissent'],0],['Quel élément ne change pas ?',['Le salaire','Le nombre de jours libres','La durée de chaque journée'],0]]},
 {id:'r8',minDay:25,title:'Bénévolat étudiant',text:'De plus en plus d’étudiants choisissent de faire du bénévolat quelques heures par semaine. Certains veulent rencontrer de nouvelles personnes, d’autres souhaitent acquérir une expérience utile pour leur futur travail. Cette activité demande du temps, mais plusieurs associations proposent des horaires flexibles.',qs:[['Pourquoi certains font-ils du bénévolat ?',['Pour acquérir une expérience','Pour éviter les études','Pour gagner un salaire élevé'],0],['Quelle difficulté est mentionnée ?',['Cela demande du temps','Il faut déménager','Les horaires sont toujours fixes'],0],['Que proposent plusieurs associations ?',['Des horaires flexibles','Un logement gratuit','Des cours obligatoires'],0]]},
 {id:'r9',minDay:31,title:'Réseaux sociaux et information',text:'Les réseaux sociaux permettent de recevoir rapidement des informations, mais ils peuvent aussi favoriser la diffusion de nouvelles fausses ou incomplètes. Des enseignants recommandent donc aux jeunes de comparer plusieurs sources avant de partager un contenu. Selon eux, cette habitude développe aussi l’esprit critique.',qs:[['Quel avantage est mentionné ?',['Recevoir rapidement des informations','Éviter toute erreur','Remplacer les enseignants'],0],['Quel risque est cité ?',['Des informations fausses ou incomplètes','Une connexion trop rapide','Le manque de téléphones'],0],['Que recommandent les enseignants ?',['Comparer plusieurs sources','Partager immédiatement','Ne jamais lire en ligne'],0]]},
 {id:'r10',minDay:35,title:'Tourisme durable',text:'Certaines destinations cherchent à limiter les effets négatifs du tourisme de masse. Elles encouragent les visiteurs à utiliser les transports publics, à consommer dans les commerces locaux et à voyager hors saison. Ces mesures peuvent réduire la pression sur les habitants, mais elles demandent aussi une meilleure organisation des services touristiques.',qs:[['Quel objectif est recherché ?',['Limiter les effets négatifs du tourisme','Attirer plus de voitures','Fermer les commerces locaux'],0],['Que conseille-t-on aux visiteurs ?',['Utiliser les transports publics','Voyager seulement en été','Éviter les commerces locaux'],0],['Quelle difficulté est évoquée ?',['Mieux organiser les services','Supprimer les habitants','Réduire tous les transports'],0]]}
];
const V13_LISTENINGS=[
 {id:'l1',minDay:1,title:'Message simple',script:'Bonjour Marie. Je suis devant le café de la gare. J’arrive avec dix minutes de retard. Attends-moi à l’intérieur, s’il te plaît.',qs:[['Où se trouve la personne ?',['Près de la gare','À l’école','À l’aéroport'],0],['Quel retard annonce-t-elle ?',['10 minutes','20 minutes','1 heure'],0],['Que doit faire Marie ?',['Attendre à l’intérieur','Rentrer chez elle','Prendre un train'],0]]},
 {id:'l2',minDay:1,title:'Horaires de magasin',script:'Bonjour. Le magasin est ouvert du lundi au samedi de neuf heures à dix-neuf heures. Le dimanche, nous sommes fermés. Merci de votre visite.',qs:[['Quels jours le magasin est-il ouvert ?',['Du lundi au samedi','Seulement dimanche','Du mardi au vendredi'],0],['À quelle heure ferme-t-il ?',['19 h','9 h','17 h'],0],['Quel jour est-il fermé ?',['Dimanche','Samedi','Lundi'],0]]},
 {id:'l3',minDay:1,title:'Invitation',script:'Salut ! Samedi soir, nous faisons un dîner chez moi à vingt heures. Tu peux venir avec ton ami. Apporte seulement quelque chose à boire.',qs:[['Quand a lieu le dîner ?',['Samedi soir','Dimanche midi','Vendredi matin'],0],['À quelle heure ?',['20 h','18 h','22 h'],0],['Que faut-il apporter ?',['Quelque chose à boire','Un cadeau obligatoire','Un repas complet'],0]]},
 {id:'l4',minDay:5,title:'Annonce de gare',script:'Attention s’il vous plaît. Le train à destination de Lyon, prévu à dix-sept heures vingt, partira finalement de la voie huit avec quinze minutes de retard. Les voyageurs sont invités à vérifier les écrans d’information.',qs:[['Quelle est la destination ?',['Lyon','Lille','Tours'],0],['De quelle voie part le train ?',['8','18','5'],0],['Quel est le retard ?',['15 minutes','50 minutes','5 minutes'],0]]},
 {id:'l5',minDay:8,title:'Message professionnel',script:'Bonjour Madame Martin. Je vous appelle au sujet de notre rendez-vous de jeudi. Je dois malheureusement le déplacer. Seriez-vous disponible vendredi matin vers dix heures ? Vous pouvez me rappeler avant dix-huit heures.',qs:[['Quel rendez-vous change ?',['Celui de jeudi','Celui de lundi','Celui de samedi'],0],['Quel nouveau moment est proposé ?',['Vendredi vers 10 h','Jeudi vers 18 h','Vendredi vers 18 h'],0],['Que doit faire Madame Martin ?',['Rappeler','Envoyer un colis','Annuler définitivement'],0]]},
 {id:'l6',minDay:12,title:'Radio locale',script:'La mairie vient d’annoncer l’ouverture d’un nouveau marché le dimanche matin. Les habitants pourront y acheter des produits locaux, notamment des légumes, du fromage et du pain. La circulation sera interdite dans la rue principale entre sept heures et quatorze heures.',qs:[['Quand ouvre le marché ?',['Dimanche matin','Samedi soir','Lundi matin'],0],['Que vendra-t-on ?',['Des produits locaux','Des voitures','Des billets de train'],0],['Jusqu’à quelle heure la rue est-elle fermée ?',['14 h','7 h','20 h'],0]]},
 {id:'l7',minDay:19,title:'Conseil de santé',script:'Pour mieux dormir, les spécialistes recommandent de réduire les écrans avant le coucher, de garder des horaires réguliers et d’éviter le café en fin de journée. Ils rappellent aussi qu’une activité physique régulière peut améliorer la qualité du sommeil.',qs:[['Que faut-il réduire avant de dormir ?',['Les écrans','L’eau','Les livres'],0],['Quand faut-il éviter le café ?',['En fin de journée','Le matin','À midi uniquement'],0],['Quelle activité peut aider ?',['L’activité physique','Regarder la télévision','Dormir toute la journée'],0]]},
 {id:'l8',minDay:25,title:'Interview sur le travail',script:'Pour moi, le télétravail est surtout utile deux jours par semaine. Je gagne presque une heure de transport, mais j’aime aussi retrouver mes collègues au bureau pour discuter des projets. Travailler toujours seul serait difficile.',qs:[['Quel avantage cite la personne ?',['Gagner du temps de transport','Gagner plus d’argent','Travailler moins de jours'],0],['Pourquoi aime-t-elle aller au bureau ?',['Pour voir ses collègues','Pour prendre le train','Pour manger gratuitement'],0],['Quelle limite évoque-t-elle ?',['Toujours travailler seul serait difficile','Le bureau est fermé','Le télétravail est interdit'],0]]},
 {id:'l9',minDay:31,title:'Chronique environnement',script:'Plusieurs villes veulent réduire la place de la voiture dans le centre. Elles développent les pistes cyclables et améliorent les transports publics. Les commerçants sont parfois inquiets, mais certaines études montrent que les zones piétonnes peuvent aussi attirer davantage de visiteurs.',qs:[['Que veulent réduire les villes ?',['La place de la voiture','Les transports publics','Les pistes cyclables'],0],['Qui est parfois inquiet ?',['Les commerçants','Les cyclistes','Les enseignants'],0],['Quel effet positif est évoqué ?',['Attirer plus de visiteurs','Fermer les centres-villes','Réduire les magasins'],0]]},
 {id:'l10',minDay:35,title:'Débat sur les écrans',script:'Une psychologue explique que les écrans ne sont pas négatifs en eux-mêmes. Selon elle, le problème vient surtout du temps d’utilisation et du type de contenu. Elle conseille aux familles de fixer des règles claires tout en discutant avec les adolescents de leurs habitudes numériques.',qs:[['Quel est le problème principal selon la psychologue ?',['Le temps et le type d’utilisation','Tous les écrans sans exception','Le prix des téléphones'],0],['Que conseille-t-elle aux familles ?',['Fixer des règles claires','Interdire toute technologie','Ne jamais discuter'],0],['Avec qui faut-il discuter ?',['Les adolescents','Les commerçants','Les touristes'],0]]}
];
