'use strict';
const QUOTAS={light:{grammar:5,application:1,listening:1,reading:1,writing:1,speaking:1,vocab:20,review:8},standard:{grammar:8,application:2,listening:2,reading:2,writing:1,speaking:2,vocab:30,review:12},high:{grammar:10,application:3,listening:3,reading:3,writing:2,speaking:3,vocab:40,review:15}};
const GRAMMAR_EXTRA={
 present:[['Vous ___ à Paris depuis deux ans.',['habitez','habite','habiter'],0,'Avec vous au présent : vous habitez.'],['Mes amis ___ souvent le français ensemble.',['pratiquent','pratique','pratiquer'],0,'Sujet pluriel : ils/elles pratiquent.']],
 negation:[['Nous n’___ pas de voiture.',['avons','sommes','faisons'],0,'La négation encadre le verbe : nous n’avons pas.'],['Elle ne sort ___.',['jamais','pas jamais','rien de'],0,'ne…jamais exprime une fréquence nulle.']],
 questions:[['___ de temps dure le trajet ?',['Combien','Où','Pourquoi'],0,'Combien de temps sert à demander une durée.'],['___ préférez-vous, le train ou le bus ?',['Que','Où','Quand'],0,'Que préférez-vous ? demande un choix.']],
 modals:[['Vous ___ attendre quelques minutes.',['devez','devez de','voulez de'],0,'devoir + infinitif : vous devez attendre.'],['Nous ___ partir plus tôt si nécessaire.',['pouvons','pouvons de','pouvoir'],0,'pouvoir + infinitif : nous pouvons partir.']],
 articles:[['Elle achète un kilo ___ tomates.',['de','des','du'],0,'Après une quantité : un kilo de tomates.'],['Nous mangeons ___ soupe ce soir.',['de la','du','des'],0,'souple est féminin singulier : de la soupe.']],
 adjectives:[['Un expérience très ___.',['intéressante','intéressant','intéressants'],0,'expérience est féminin : intéressante.'],['Des quartiers très ___.',['calmes','calme','calmées'],0,'quartiers est masculin pluriel : calmes.']],
 prepositions:[['Je travaille ___ Lyon.',['à','en','au'],0,'Ville : à Lyon.'],['Le cours commence ___ neuf heures.',['à','en','depuis'],0,'Heure précise : à neuf heures.']],
 pc:[['Samedi, nous ___ un musée.',['avons visité','visitions','visitons'],0,'Événement terminé : passé composé.'],['Elle ___ très tard hier soir.',['est rentrée','a rentrée','rentrait toujours'],0,'rentrer peut se construire avec être pour le déplacement : elle est rentrée.']],
 imparfait:[['À cette époque, nous ___ près de la mer.',['habitions','avons habité hier','habiterons'],0,'Situation passée durable : imparfait.'],['Tous les étés, il ___ chez ses cousins.',['restait','est resté une fois','reste'],0,'Habitude passée répétée : imparfait.']],
 pcimp:[['Pendant que je ___, quelqu’un ___ à la porte.',['travaillais / a frappé','ai travaillé / frappait','travaille / frappe'],0,'Action en cours à l’imparfait + événement ponctuel au passé composé.'],['La rue ___ calme quand l’accident ___.',['était / a eu lieu','a été / avait lieu','est / aura lieu'],0,'État de fond : imparfait ; événement : passé composé.']],
 future:[['La semaine prochaine, je ___ mes résultats.',['recevrai','recevais','ai reçu'],0,'Moment futur : futur simple.'],['Nous ___ visiter Bordeaux ce week-end.',['allons','avons','sommes de'],0,'aller + infinitif : futur proche.']],
 codcoi:[['J’écris à ma sœur → je ___ écris.',['lui','la','y'],0,'à + personne singulier : lui.'],['Je connais ces personnes → je ___ connais.',['les','leur','en'],0,'COD pluriel : les.']],
 yen:[['Vous pensez à votre projet ? Oui, j’___ pense.',['y','en','le'],0,'penser à + chose → y.'],['Vous avez besoin de temps ? Oui, j’___ ai besoin.',['en','y','le'],0,'avoir besoin de + chose → en.']],
 relatives:[['La personne ___ parle est ma collègue.',['qui','que','où'],0,'Le pronom est sujet de parle : qui.'],['C’est le quartier ___ nous avons habité.',['où','qui','que de'],0,'Lieu : où.']],
 conditionnel:[['À votre place, je ___ le directeur.',['contacterais','contacte hier','contacterai hier'],0,'Conseil hypothétique : conditionnel.'],['Est-ce qu’il ___ possible de changer la date ?',['serait','sera hier','était demain'],0,'Formule polie : serait-il possible… ?']],
 connectors:[['Quel connecteur introduit une cause ?',['parce que','donc','cependant'],0,'parce que introduit une cause.'],['Quel connecteur permet de nuancer ?',['pourtant','donc','enfin de'],0,'pourtant introduit une opposition/nuance.']],
 comparison:[['Le vélo est ___ écologique que la voiture.',['plus','très de','autant'],0,'plus + adjectif + que.'],['Cette solution est ___ pratique que l’autre.',['aussi','autant de','beaucoup de'],0,'aussi + adjectif + que.']],
 opinion:[['Pour annoncer un premier argument…',['D’abord,…','Pour conclure,…','Malheureusement que…'],0,'D’abord introduit un premier point.'],['Pour apporter une nuance…',['Cependant,…','Par exemple,…','En premier de…'],0,'Cependant permet de nuancer/opposer.']]
};
function grammarQuestions(g){return g.qs.concat(GRAMMAR_EXTRA[g.id]||[])}
const V13_APPLICATION=[
 {id:'a1',minDay:1,topic:'Service',title:'Demander de répéter',task:'Vous ne comprenez pas une information. Demandez poliment à la personne de répéter et de parler plus lentement.',keys:['pouvez','répéter','lentement'],chunks:['Excusez-moi, je n’ai pas compris.','Pouvez-vous répéter, s’il vous plaît ?','Pouvez-vous parler plus lentement ?']},
 {id:'a2',minDay:1,topic:'Restaurant',title:'Commander simplement',task:'Commandez un plat et une boisson, puis demandez le prix ou une information sur le menu.',keys:['voudrais','boire','combien'],chunks:['Je voudrais…','Qu’est-ce que vous avez comme… ?','Combien coûte… ?']},
 {id:'a3',minDay:1,topic:'Transport',title:'Acheter un billet',task:'Demandez un billet pour une ville, précisez le jour et demandez l’heure de départ.',keys:['billet','demain','heure'],chunks:['Je voudrais un billet pour…','Pour demain, s’il vous plaît.','À quelle heure part… ?']},
 {id:'a4',minDay:5,topic:'Hôtel',title:'房间太吵',task:'Expliquez le problème et demandez poliment une autre chambre.',keys:['problème','voudrais','pourriez'],chunks:['Le problème, c’est que…','Je voudrais…','Pourriez-vous… ?']},
 {id:'a5',minDay:8,topic:'Voyage',title:'火车取消',task:'Votre train est annulé. Demandez une autre solution au guichet et réagissez à une proposition.',keys:['train','annul','solution'],chunks:['Mon train a été annulé.','Quelle solution pouvez-vous proposer ?','Cela ne me convient pas parce que…']},
 {id:'a6',minDay:12,topic:'Santé',title:'预约医生',task:'Expliquez un problème de santé, précisez depuis quand et demandez un rendez-vous.',keys:['rendez-vous','depuis','mal'],chunks:['J’ai mal à… depuis…','Je voudrais prendre rendez-vous.','Est-ce que vous avez une disponibilité ?']},
 {id:'a7',minDay:15,topic:'Logement',title:'邻居噪音',task:'Expliquez poliment le problème à votre voisin et proposez une solution concrète.',keys:['bruit','soir','pourriez'],chunks:['Je voulais vous parler de…','Pourriez-vous… ?','On pourrait peut-être…']},
 {id:'a8',minDay:19,topic:'Travail',title:'调整工作时间',task:'Demandez à commencer plus tôt pendant une semaine et justifiez votre demande.',keys:['semaine','parce','propose'],chunks:['Je souhaiterais…','C’est parce que…','Je vous propose de…']},
 {id:'a9',minDay:22,topic:'Études',title:'缺课补课',task:'Écrivez au professeur : expliquez votre absence et demandez comment rattraper le cours.',keys:['cours','rattrap','pourriez'],chunks:['Je ne pourrai pas assister…','Pourriez-vous m’indiquer… ?','Je voudrais rattraper…']},
 {id:'a10',minDay:25,topic:'Consommation',title:'商品退款',task:'Un produit ne fonctionne pas. Expliquez la situation, refusez une proposition qui ne vous convient pas et demandez une solution.',keys:['fonctionne','rembours','solution'],chunks:['Le produit ne fonctionne plus.','Je préférerais…','Je souhaiterais être remboursé.']},
 {id:'a11',minDay:28,topic:'Loisirs',title:'说服朋友出行',task:'Votre ami hésite à partir en week-end. Essayez de le convaincre avec deux arguments et répondez à une objection.',keys:['week-end','parce','pourrait'],chunks:['On pourrait…','Ce serait une bonne idée parce que…','Je comprends, mais…']},
 {id:'a12',minDay:31,topic:'Opinion',title:'学校里的手机',task:'Donnez votre opinion : faut-il limiter le téléphone à l’école ? Deux raisons, un exemple et une nuance.',keys:['avis','parce','exemple'],chunks:['À mon avis,…','D’abord,…','Par exemple,…','Cependant,…']}
];
