'use strict';
const V14_VERSION='1.4';
S.prodDone=S.prodDone||{};
const _dailyV13=daily;
daily=function(day=S.selectedDay){const d=_dailyV13(day);if(typeof d.grammarProduction!=='number')d.grammarProduction=0;return d};
S.version=V14_VERSION;save();
top=function(title,sub){return `<div class="top"><div><div class="eyebrow">DELF50 · WEB V${V14_VERSION}</div><h1>${title}</h1><div class="muted">${sub}</div></div></div>`};

const _buildTasksV13=buildTasks;
buildTasks=function(day){const t=_buildTasksV13(day),q=quota(),pq=productionQuota();t[0].desc=`${DAYS[day-1][1]}：完成 ${q.grammar} 道客观题 + ${pq} 句主动产出；产出包含改写、纠错、造句和口头调用。`;return t};

taskCount=function(id,day=S.selectedDay){const d=daily(day),q=quota(),pq=productionQuota();if(id==='grammar')return[Math.min(d.grammar,q.grammar)+Math.min(d.grammarProduction,pq),q.grammar+pq];if(id==='app')return[d.application,q.application];if(id==='listen')return[d.listening,q.listening];if(id==='read')return[d.reading,q.reading];if(id==='write')return[d.writing,q.writing];if(id==='speak')return[d.speaking,q.speaking];if(id==='vocab'||id==='review')return[S.taskDone[dayKey(day,id)]?1:0,1];return[0,1]};
totalCompletedTasks=function(){let n=Object.values(S.taskDone||{}).filter(Boolean).length;for(const d of Object.values(S.daily||{}))n+=(d.grammar||0)+(d.grammarProduction||0)+(d.application||0)+(d.listening||0)+(d.reading||0)+(d.writing||0)+(d.speaking||0);return n};

function prodKey(gid,i){return `${S.selectedDay}:${gid}:${i}`}
function productionCards(g){const all=GRAMMAR_PRODUCTION[g.id]||[],need=Math.ceil(productionQuota()/2),items=all.slice(0,need);return items.map((p,i)=>{const k=prodKey(g.id,i),done=!!S.prodDone[k];return `<div class="node"><div class="row wrap"><div style="flex:1"><b>主动产出 ${i+1}</b><div class="muted" style="margin-top:4px">${esc(p)}</div><div class="source">每项按 2 个句子/口头单位记录；它是训练量，不计入客观正确率。</div></div><button class="btn ${done?'secondary':''} small" data-prod-done="${i}" data-prod-g="${g.id}" ${done?'disabled':''}>${done?'✓ 已记录':'完成2句'}</button></div></div>`}).join('')}

function today(){const d=DAYS[S.selectedDay-1],tasks=buildTasks(S.selectedDay),done=dayDoneMinutes(),total=plannedMinutes(),q=quota(),pq=productionQuota();return `${top(`Day ${S.selectedDay} · ${d[0]}`,`${phase()} · ${d[4]}`)}${dayControls()}<div class="card hero"><div class="row wrap"><div><div class="eyebrow" style="color:#d4eee7">TODAY PLAN</div><h2>${phase()}</h2><div class="muted" style="color:#d8eee8">${phaseNote()}</div></div><div><b>${fmtMin(total)}</b><div class="muted" style="color:#d8eee8">计划学习量</div></div></div><div class="grid3" style="margin-top:12px"><div class="metric"><span>今日完成</span><b>${Math.round(done/total*100)||0}%</b><span>${fmtMin(Math.round(done))} / ${fmtMin(total)}</span></div><div class="metric"><span>听读客观题</span><b>${(q.listening+q.reading)*3}</b><span>${q.listening}组听力 + ${q.reading}篇阅读</span></div><div class="metric"><span>主动输出</span><b>${q.application+q.writing+q.speaking}</b><span>应用 + 写作 + 口语</span></div></div></div><div class="card"><div class="row"><b>今日学习块</b><span class="pill blue">${LEVELS[S.intensity].label} · ${fmtMin(total)}</span></div>${tasks.map(t=>{const [a,b]=taskCount(t.id);const auto=!['vocab','review'].includes(t.id);let target;if(t.id==='grammar')target=`${a}/${b}微任务`;else if(['listen','read'].includes(t.id))target=`${a}/${b}组`;else if(['write','speak','app'].includes(t.id))target=`${a}/${b}项`;else target=`${a}/${b}`;const goto=t.id==='grammar'?'grammar':['listen','read'].includes(t.id)?'input':['write','speak','app'].includes(t.id)?'output':null;return `<div class="task" ${goto?`data-goto="${goto}"`:''}><div class="time">${t.min}<br>min</div><div><b>${t.name}</b> <span class="pill ${a>=b?'':'blue'}">${target}</span><div class="desc">${t.desc}</div></div>${auto?`<div class="check ${a>=b?'done':''}">${a>=b?'✓':'→'}</div>`:`<button class="check ${S.taskDone[dayKey(S.selectedDay,t.id)]?'done':''}" data-task="${t.id}">${S.taskDone[dayKey(S.selectedDay,t.id)]?'✓':'○'}</button>`}</div>`}).join('')}</div><div class="card"><b>强度与实际题量</b><div class="callout blue"><b>5小时：</b>语法 8 道客观题 + 6 句产出；听力 2 组；阅读 2 篇；写作 1 项；口语 2 轮；应用 2 项；约 25 次词块回忆。<br><b>6.5小时：</b>语法 10 道 + 8 句产出；听力/阅读各 3 组；写作 1 项；口语/应用各 3 项；约 35 次词块回忆。<br><b>8小时：</b>语法 12 道 + 10 句产出；听力/阅读各 4 组；写作 2 项；口语/应用各 4 项；约 45 次词块回忆。<br>增加的是同阶段训练量和重复调用，不会提前解锁超阶段语法。</div></div><div class="card"><b>循序渐进规则</b><div class="callout good">${S.selectedDay<=18?'约 25–35% 新知识 + 65–75% 操练/复习/应用。高强度只增加当前及已学节点的训练量。':S.selectedDay<=30?'以旧语法迁移到真实任务为主；新增情境比新增语法更重要。':S.selectedDay<=40?'以 DELF 听读写说任务、时间控制和信息处理为主。':'模拟 → 错因定位 → 微训练 → 再模拟，不再系统扩新语法。'}</div></div>`}

grammar=function(){const d=daily(),qz=quota(),pq=productionQuota(),rec=recommendedGrammarNode(),g=GRAMMAR[UI.gNode],qs=grammarQuestions(g),q=qs[UI.gQ%qs.length],st=S.grammar.skill[g.id]||{a:0,c:0};return `${top('Grammar Gym','客观正确率与主动产出分开记录：前者可测量，后者证明你是否真正调用过语法。')}<div class="grid2"><div><div class="card"><div class="row wrap"><div><b>今日语法客观题</b><div class="muted">当前/已学节点循环，不用未来节点凑题。</div></div><span class="pill ${d.grammar>=qz.grammar?'':'blue'}">${d.grammar}/${qz.grammar}</span></div><div class="barrow"><div class="bar"><i style="width:${Math.min(100,Math.round(d.grammar/qz.grammar*100)||0)}%"></i></div></div></div><div class="card"><span class="pill">${g.level}</span><span class="pill blue">${g.use}</span><h2>${UI.gNode+1}. ${g.name}</h2><div class="callout blue">例句：${g.ex.map(esc).join(' · ')}</div><div class="divider"></div><div class="muted">节点客观正确率：${st.a?pct(st.c,st.a)+'%':'未评估'} · 已做 ${st.a} 题</div><h2>${esc(q[0])}</h2>${q[1].map((o,i)=>`<button class="opt ${UI.gSel===i?'on':''} ${UI.gAnswered?(i===q[2]?'good':UI.gSel===i?'bad':''):''}" data-gopt="${i}" ${UI.gAnswered?'disabled':''}>${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}${UI.gAnswered?`<div class="callout ${UI.gSel===q[2]?'good':'bad'}"><b>${UI.gSel===q[2]?'正确':'需要修复'}</b><br>${q[3]}</div><button class="btn" id="nextGQ">下一道客观题</button>`:`<button class="btn" id="submitG" ${UI.gSel===null?'disabled':''}>提交答案</button>`}</div><div class="card"><div class="row wrap"><div><b>主动产出 · ${g.name}</b><div class="muted">目标 ${pq} 句；变形、纠错、造句、口头调用。完成量不改变客观正确率。</div></div><span class="pill ${d.grammarProduction>=pq?'':'blue'}">${Math.min(d.grammarProduction,pq)}/${pq}句</span></div>${productionCards(g)}</div></div><div><div class="card"><div class="row"><b>语法知识地图</b><button class="btn secondary small" id="recommendedG">跳到今日推荐</button></div>${GRAMMAR.map((x,i)=>{const z=S.grammar.skill[x.id]||{a:0,c:0},allowed=S.selectedDay>18||i<=Math.min(17,S.selectedDay-1);return `<div class="node ${i===UI.gNode?'current':''}" data-gnode="${i}"><b>${i+1}. ${x.name}</b> <span class="pill">${x.level}</span>${!allowed?'<span class="pill warn">后续节点</span>':''}<div class="muted">${x.use} · ${z.a?pct(z.c,z.a)+'%':'未评估'}</div></div>`}).join('')}</div><div class="card"><b>为什么不只刷选择题？</b><div class="callout warn">选择题只能证明你“认得”结构。DELF 写作与口语需要主动调用，所以每个语法节点必须同时完成改写、纠错、自由造句和口头输出。这里把两种证据分开保存，避免把训练量冒充能力。</div></div></div></div>`};

const _bindV13=bind;
bind=function(){_bindV13();document.querySelectorAll('[data-prod-done]').forEach(b=>b.onclick=()=>{const gid=b.dataset.prodG,i=Number(b.dataset.prodDone),k=prodKey(gid,i);if(S.prodDone[k])return;S.prodDone[k]=true;daily().grammarProduction+=2;if(!S.startedAt)S.startedAt=new Date().toISOString();save();render()})};

progressPage=function(){const completed=totalCompletedTasks();return `${top('进度与存储','能力评估只来自可验证的数据；主动产出、写作和口语只显示训练证据。')}<div class="card"><h2>客观测量</h2><div class="grid3">${measured('语法客观正确率',S.grammar)}${measured('阅读客观正确率',S.reading)}${measured('听力客观正确率',S.listening)}</div><div class="callout warn" style="margin-top:10px">少量题目的百分比波动很大。每项至少积累 20–30 道客观题，再观察趋势；写作和口语目前不生成自动能力分数。</div></div><div class="card"><h2>训练证据（不是能力分数）</h2><div class="grid3"><div class="metric"><span>实际微任务记录</span><b>${completed}</b><span>客观题/产出/任务</span></div><div class="metric"><span>应用情境</span><b>${S.application.count}</b><span>真实功能表达</span></div><div class="metric"><span>写作任务</span><b>${S.writing.count}</b><span>保存字数/结构</span></div><div class="metric"><span>口语任务</span><b>${S.speaking.count}</b><span>不生成水平百分比</span></div><div class="metric"><span>口语录音</span><b>${fmtSec(S.speaking.totalSec)}</b><span>累计录音时长</span></div><div class="metric"><span>待复习错题</span><b>${S.errors.length}</b><span>错误修复队列</span></div></div></div><div class="card"><h2>连续学习存储</h2><div class="callout good">学习状态每次操作后自动写入 localStorage；口语录音写入 IndexedDB。升级版本继续沿用同一数据键，因此不会因为 V1.4 内容增强而自动清空旧学习记录。</div><div class="row wrap" style="margin-top:10px"><button class="btn" id="exportBtn">导出学习备份</button><label class="btn secondary" style="cursor:pointer">导入备份<input id="importFile" type="file" accept="application/json" style="display:none"></label><button class="btn secondary" id="resetBtn">重置为全0</button></div><div class="storage">最后保存：${S.lastSavedAt?new Date(S.lastSavedAt).toLocaleString():'尚未开始学习'} · 数据版本 ${V14_VERSION}</div></div>${errorsPage()}`};

exportBackup=function(){const data={app:'DELF50',version:V14_VERSION,exportedAt:new Date().toISOString(),state:S,note:'口语音频保存在浏览器 IndexedDB 中，不包含在 JSON 备份内。'};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`delf50-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
render();
