'use strict';
// V1.4: deepen the workload without advancing the curriculum prematurely.
Object.assign(QUOTAS.light,{grammar:8,application:2,listening:2,reading:2,writing:1,speaking:2,vocab:25,review:10});
Object.assign(QUOTAS.standard,{grammar:10,application:3,listening:3,reading:3,writing:1,speaking:3,vocab:35,review:15});
Object.assign(QUOTAS.high,{grammar:12,application:4,listening:4,reading:4,writing:2,speaking:4,vocab:45,review:20});
const GRAMMAR_PRODUCTION_QUOTA={light:6,standard:8,high:10};
function productionQuota(){return GRAMMAR_PRODUCTION_QUOTA[S.intensity]||8}

// Enough unique objective items for Day 1 and richer review on later days.
const GRAMMAR_DEPTH_Q={
 present:[
  ['Je ___ étudiant en France.',['suis','ai','vais'],0,'être sert ici à identifier la personne : je suis étudiant.'],
  ['Nous ___ deux cours aujourd’hui.',['avons','sommes','allons de'],0,'avoir exprime la possession / disponibilité : nous avons deux cours.'],
  ['Ils ___ au travail en métro.',['vont','font','sont de'],0,'aller au présent : ils vont.'],
  ['Tu ___ du sport le samedi.',['fais','fait','faire'],0,'faire avec tu : tu fais.'],
  ['Vous ___ souvent ici ?',['venez','vient','venir'],0,'venir avec vous : vous venez.'],
  ['On ___ français pendant le cours.',['parle','parlent','parler'],0,'on prend la 3e personne du singulier : on parle.'],
  ['Elles ___ très motivées.',['sont','ont de','être'],0,'être avec elles : elles sont.']
 ],
 negation:[['Je ___ veux ___ sortir ce soir.',['ne / pas','pas / ne','ne / rien'],0,'ne + verbe + pas.'],['Nous n’avons ___ de cours vendredi.',['pas','jamais pas','rien de'],0,'n’avoir pas de + nom.'],['Elle ne mange ___ de viande.',['jamais','pas jamais','aucun de'],0,'ne…jamais exprime une habitude inexistante.']],
 questions:[['___ est votre adresse ?',['Quelle','Où de','Combien'],0,'quelle adresse ?'],['___ partez-vous ? — Demain matin.',['Quand','Où','Pourquoi de'],0,'quand demande le moment.'],['___ personnes viennent ?',['Combien de','Quel de','Pourquoi'],0,'combien de + nom pluriel.']],
 modals:[['Je ___ finir ce travail aujourd’hui.',['dois','dois de','peux à'],0,'devoir + infinitif.'],['Est-ce que je ___ entrer ?',['peux','peux de','pouvoir'],0,'pouvoir + infinitif.'],['Nous ___ réserver pour samedi.',['voudrions','voudrions de','voulons à'],0,'conditionnel de vouloir pour une demande polie.']],
 articles:[['Il boit beaucoup ___ eau.',['d’','de la','du'],0,'beaucoup de devient d’ devant voyelle.'],['Nous prenons ___ café après le déjeuner.',['un','de un','des'],0,'un café = une unité / une boisson.'],['Elle achète ___ pain et ___ fromage.',['du / du','de la / de la','des / des'],0,'noms massifs masculins : du.']],
 adjectives:[['Une histoire ___.',['intéressante','intéressant','intéressantes'],0,'histoire est féminin singulier.'],['Deux étudiants ___.',['français','française','françaises'],0,'masculin pluriel : français.'],['Mes amies sont très ___.',['sympathiques','sympathique','sympathiquées'],0,'pluriel : sympathiques.']],
 prepositions:[['Nous allons ___ cinéma ce soir.',['au','à la','en'],0,'à + le = au.'],['Elle revient ___ Italie.',['d’','de la','du'],0,'venir/revenir d’Italie.'],['Je suis ici ___ lundi.',['depuis','pendant de','à'],0,'depuis + point de départ.']],
 pc:[['J’___ mes amis hier.',['ai appelé','appelais toujours','appelle demain'],0,'action terminée hier : passé composé.'],['Elle ___ à Paris samedi.',['est partie','a partie','partait une fois'],0,'partir se conjugue avec être.'],['Vous ___ le message ?',['avez reçu','êtes reçu','receviez demain'],0,'recevoir avec avoir au passé composé.']],
 imparfait:[['Quand il était jeune, il ___ beaucoup.',['lisait','a lu une fois','lira'],0,'habitude passée : imparfait.'],['La maison ___ très calme.',['était','a été soudain','sera'],0,'description / état de fond : imparfait.'],['Nous ___ chaque été en Bretagne.',['allions','sommes allés hier','irons'],0,'habitude répétée : imparfait.']],
 pcimp:[['Je ___ quand tu m’___.',['cuisinais / as appelé','ai cuisiné / appelais','cuisine / appelles'],0,'action en cours + événement ponctuel.'],['Il ___ froid quand nous ___.',['faisait / sommes sortis','a fait / sortions toujours','fera / sortons'],0,'météo de fond à l’imparfait + sortie au passé composé.'],['Tous les dimanches, ils ___ au parc, mais dimanche dernier ils ___ chez eux.',['allaient / sont restés','sont allés / restaient','vont / restent'],0,'habitude à l’imparfait, exception au passé composé.']],
 future:[['Cet été, nous ___ en Espagne.',['irons','allions','sommes allés'],0,'futur simple : nous irons.'],['Je ___ appeler le médecin tout de suite.',['vais','ai','suis'],0,'futur proche : je vais appeler.'],['Vous ___ bientôt une confirmation.',['recevrez','receviez','avez reçu hier'],0,'futur simple : vous recevrez.']],
 codcoi:[['Je vois Marie → je ___ vois.',['la','lui','en'],0,'COD féminin singulier : la.'],['Nous répondons aux clients → nous ___ répondons.',['leur','les','y'],0,'à + personnes pluriel : leur.'],['Il invite ses collègues → il ___ invite.',['les','leur','en'],0,'COD pluriel : les.']],
 yen:[['Tu vas au marché ? Oui, j’___ vais.',['y','en','le'],0,'lieu introduit par à → y.'],['Vous prenez trois billets ? Oui, j’___ prends trois.',['en','y','les'],0,'quantité + nom → en, la quantité reste.'],['Elle revient de Paris ? Oui, elle ___ revient.',['en','y','la'],0,'de + lieu/chose → en.']],
 relatives:[['La femme ___ travaille ici est médecin.',['qui','que','où'],0,'qui est sujet de travaille.'],['Le restaurant ___ nous aimons est fermé.',['que','qui','où'],0,'que est COD de aimons.'],['Le jour ___ je suis arrivé, il pleuvait.',['où','qui','que'],0,'où peut exprimer un moment.']],
 conditionnel:[['Je ___ réserver une table.',['voudrais','voudrai hier','voulais demain'],0,'je voudrais = demande polie.'],['Vous ___ parler moins fort ?',['pourriez','pouvez de','pourriez de'],0,'pourriez-vous + infinitif.'],['À ta place, nous ___ plus tôt.',['partirions','partions demain','partirons hier'],0,'conseil hypothétique au conditionnel.']],
 connectors:[['Il pleut ; ___, je prends un parapluie.',['donc','cependant','par exemple'],0,'donc introduit la conséquence.'],['J’aime ce quartier. ___, il est assez cher.',['Cependant','Donc','Parce que de'],0,'cependant introduit une nuance/opposition.'],['Je fais plusieurs sports ; ___, je nage deux fois par semaine.',['par exemple','pourtant que','donc de'],0,'par exemple introduit une illustration.']],
 comparison:[['Ce train est ___ cher que l’autre.',['moins','moins de','très'],0,'moins + adjectif + que.'],['Paris est ___ animé que cette petite ville.',['plus','autant de','beaucoup'],0,'plus + adjectif + que.'],['Les deux solutions sont ___ pratiques.',['aussi','autant de','plus de'],0,'aussi + adjectif.']],
 opinion:[['Pour donner une raison…',['Parce que…','Pour conclure…','À demain…'],0,'parce que introduit une raison.'],['Pour présenter une objection…',['En revanche,…','Par exemple,…','Tout d’abord parce…'],0,'en revanche marque le contraste.'],['Pour résumer votre position…',['En résumé,…','À cause de…','D’un côté seulement…'],0,'en résumé permet de synthétiser.']]
};
Object.entries(GRAMMAR_DEPTH_Q).forEach(([id,items])=>{if(!GRAMMAR_EXTRA[id])GRAMMAR_EXTRA[id]=[];GRAMMAR_EXTRA[id].push(...items)});

const GRAMMAR_PRODUCTION={
 present:['写2句介绍你现在的身份/状态，分别使用 être 和 avoir。','写2句日常习惯，分别使用 aller 和 faire。','把一个 je 句改写成 nous，再改写成 ils/elles。','用 souvent / parfois 各写1句现在时。','不看提示，口头说2句“今天我做什么/去哪里”。'],
 negation:['把2个肯定句改成 ne…pas。','分别用 ne…jamais 和 ne…plus 写1句。','写2句说明你“不喜欢/不想要”的东西。','把一个含 un/du 的句子改成否定，注意 de。','口头说2句你这周“不做”的事。'],
 questions:['把2个陈述句改成 est-ce que 疑问句。','分别用 où / quand 提2个问题。','分别用 pourquoi / combien de 提2个问题。','为“订课程”情境准备2个礼貌问题。','不看文字，连续提出2个相关追问。'],
 modals:['用 pouvoir 写2个请求。','用 devoir 写2个义务。','用 vouloir / voudrais 写2个愿望或礼貌请求。','把直接命令改成2个更礼貌的请求。','口头完成：向酒店前台提出2个需求。'],
 articles:['写2句购物清单，正确使用 un/une/des。','写2句饮食表达，使用 du/de la/de l’.','把2个数量表达改成 beaucoup de / un kilo de。','把2个肯定饮食句改成否定并检查 de。','口头列出今天吃喝的4样东西。'],
 adjectives:['描述一个人，用2个不同形容词并做配合。','描述一个城市，用2个阴性形容词。','把单数名词+形容词改成复数2次。','写2组相反形容词描述两个地方。','口头描述你住的地方至少4个形容词。'],
 prepositions:['写2句说明你在哪里生活/学习，使用 à/en/au。','写2句说明持续时间，使用 depuis。','分别用 pendant 和 depuis 写1句。','写2句周末行程，正确使用地点介词。','口头说出3个时间点和对应活动。'],
 pc:['写2句“昨天完成的动作”。','把2个现在时句改成 passé composé。','写1句 avoir 助动词，1句 être 助动词。','纠正2个过去分词或助动词错误句。','口头用3个动作讲昨天晚上。'],
 imparfait:['写2句童年习惯。','写2句过去的天气/环境背景。','把2个“以前经常…”句子改成 imparfait。','写1句过去身体状态，1句过去情绪状态。','口头描述童年生活至少4句。'],
 pcimp:['写2组“背景 + 突发事件”。','给一个旅行故事写2句背景，再写1句事件。','把一个只用 passé composé 的小故事改成含 imparfait。','写2句区分“习惯”和“某一次”。','口头讲30秒小事故，至少各用1次两种过去时。'],
 future:['用 futur proche 写2个近期计划。','用 futur simple 写2个较远预测。','把2个现在时计划改成未来表达。','写1句个人计划，1句社会预测。','口头说下周计划和明年计划各2句。'],
 codcoi:['把2个重复名词改成 COD 代词。','把2个 à + 人改成 lui/leur。','写1句 le/la/les，1句 lui/leur。','纠正2个代词位置错误。','口头回答2个问题，避免重复名词。'],
 yen:['用 y 回答2个地点问题。','用 en 回答2个数量/de结构问题。','把2个重复地点/数量名词替换掉。','分别造1句 j’y… 和 j’en…。','口头连续回答4个 y/en 快问快答。'],
 relatives:['用 qui 合并2组短句。','用 que 合并2组短句。','用 où 连接地点或时间2次。','把4个短句合并成2个复合句。','口头描述一个你喜欢的地方，至少用2个关系代词。'],
 conditionnel:['用 je voudrais 写2个礼貌请求。','用 pourriez-vous 写2个请求。','用 à ta place + conditionnel 给2条建议。','把2个直接命令改成礼貌表达。','口头完成酒店/商店情境，提出3个礼貌诉求。'],
 connectors:['用 parce que / donc 连成2组因果句。','用 cependant / pourtant 写2个转折句。','用 par exemple 给2个观点补例子。','用 d’abord / ensuite / enfin 组织3句。','口头说45秒观点，至少使用3个连接词。'],
 comparison:['用 plus…que 写2个比较。','用 moins…que 写2个比较。','用 aussi…que 写2个比较。','比较两种交通工具，写4句。','口头比较两个城市/住房并做选择。'],
 opinion:['写1句明确观点 + 2个理由。','为一个观点写1个具体例子。','加入1句 cependant / en revanche 的让步。','写一个5句迷你论证：观点→理由→例子→转折→结论。','口头说1分钟观点，必须有结论。']
};

// Extra Day-1 items prevent high intensity from recycling the same text/task.
V13_APPLICATION.push({id:'a0',minDay:1,topic:'Café',title:'Demander le Wi-Fi',task:'Dans un café, demandez le mot de passe Wi-Fi, où vous pouvez vous asseoir et si vous pouvez payer par carte.',keys:['wifi','asseoir','carte'],chunks:['Excusez-moi, quel est le mot de passe Wi-Fi ?','Je peux m’asseoir ici ?','Est-ce que je peux payer par carte ?']});
V13_READINGS.push(
 {id:'r0',minDay:1,title:'Inscription à la bibliothèque',text:'La bibliothèque municipale est gratuite pour les étudiants. Pour s’inscrire, il faut présenter une pièce d’identité et un justificatif de domicile. La carte est préparée immédiatement à l’accueil. Le lundi, la bibliothèque ouvre à dix heures.',qs:[['Pour qui l’inscription est-elle gratuite ?',['Pour les étudiants','Pour tous les touristes','Pour les entreprises'],0],['Quel document faut-il présenter ?',['Une pièce d’identité','Un billet de train','Un diplôme'],0],['À quelle heure ouvre-t-elle le lundi ?',['10 h','8 h','14 h'],0]]},
 {id:'r11',minDay:15,title:'Maison médicale',text:'La maison médicale reçoit les patients sans rendez-vous le matin entre huit heures et midi. L’après-midi, il faut réserver un créneau par téléphone. En cas d’urgence grave, les patients doivent appeler le 15 et ne pas attendre sur place.',qs:[['Quand peut-on venir sans rendez-vous ?',['Le matin','Toute la journée','Seulement le soir'],0],['Comment réserver l’après-midi ?',['Par téléphone','Par courrier uniquement','À la gare'],0],['Que faire en cas d’urgence grave ?',['Appeler le 15','Attendre sur place','Envoyer un message au voisin'],0]]},
 {id:'r12',minDay:22,title:'Cours du soir',text:'Une association propose des cours du soir pour les adultes qui travaillent. Les séances ont lieu deux fois par semaine de dix-neuf heures à vingt heures trente. Les participants apprécient les petits groupes, mais certains trouvent difficile de rester concentrés après une journée de travail.',qs:[['À qui s’adressent les cours ?',['Aux adultes qui travaillent','Aux enfants uniquement','Aux touristes'],0],['Quel avantage est cité ?',['Les petits groupes','Les cours gratuits tous les jours','Les séances le matin'],0],['Quelle difficulté apparaît ?',['Rester concentré après le travail','Trouver la salle le matin','Acheter un ordinateur'],0]]},
 {id:'r13',minDay:28,title:'Réparer plutôt que jeter',text:'Dans plusieurs quartiers, des ateliers participatifs apprennent aux habitants à réparer de petits appareils. L’objectif est de réduire les déchets et d’économiser de l’argent. Les bénévoles donnent des conseils, mais ils ne peuvent pas garantir que chaque appareil sera réparé.',qs:[['Quel est un objectif des ateliers ?',['Réduire les déchets','Vendre plus d’appareils','Remplacer les magasins'],0],['Qui donne des conseils ?',['Des bénévoles','Des policiers','Des touristes'],0],['Quelle limite est précisée ?',['La réparation n’est pas garantie','Il faut acheter un nouvel appareil','Les ateliers ferment toujours'],0]]},
 {id:'r14',minDay:33,title:'Cantine plus végétale',text:'Une ville souhaite proposer davantage de plats végétariens dans les cantines scolaires. La mairie explique que cette mesure peut réduire l’impact environnemental des repas et faire découvrir de nouvelles recettes. Certains parents demandent toutefois des informations précises sur l’équilibre nutritionnel.',qs:[['Que veut faire la ville ?',['Proposer plus de plats végétariens','Fermer les cantines','Supprimer tous les légumes'],0],['Quel bénéfice est avancé ?',['Réduire l’impact environnemental','Augmenter les devoirs','Réduire le nombre d’élèves'],0],['Que demandent certains parents ?',['Des informations nutritionnelles','Des billets gratuits','Plus de devoirs'],0]]},
 {id:'r15',minDay:38,title:'Droit à la déconnexion',text:'Certaines entreprises encouragent leurs salariés à ne pas répondre aux messages professionnels le soir et le week-end. Elles espèrent ainsi mieux séparer le travail de la vie privée. Cette règle est appréciée, mais elle peut être plus difficile à appliquer dans les équipes qui travaillent avec plusieurs fuseaux horaires.',qs:[['Quel est le but principal ?',['Mieux séparer travail et vie privée','Travailler toute la nuit','Supprimer les e-mails'],0],['Quand conseille-t-on de ne pas répondre ?',['Le soir et le week-end','Seulement le lundi matin','Pendant toutes les heures de travail'],0],['Dans quel cas la règle est-elle plus difficile ?',['Avec plusieurs fuseaux horaires','Dans les petites villes','Quand il pleut'],0]]}
);
V13_LISTENINGS.push(
 {id:'l0',minDay:1,title:'Bus de quartier',script:'Bonjour. Le bus numéro douze arrive dans cinq minutes. Il va au centre-ville et s’arrête devant la mairie. Le dernier bus part à vingt-deux heures.',qs:[['Quel numéro de bus ?',['12','2','20'],0],['Où va-t-il ?',['Au centre-ville','À l’aéroport','À la plage'],0],['À quelle heure part le dernier bus ?',['22 h','12 h','20 h'],0]]},
 {id:'l11',minDay:15,title:'Pharmacie',script:'Bonjour. Pour ce médicament, prenez un comprimé le matin après le petit-déjeuner et un autre le soir. Si vous avez encore de la fièvre après trois jours, contactez votre médecin.',qs:[['Quand prendre le premier comprimé ?',['Le matin après le petit-déjeuner','À midi avant de manger','Pendant la nuit'],0],['Combien le soir ?',['Un comprimé','Trois comprimés','Aucun'],0],['Quand contacter le médecin ?',['Si la fièvre continue après trois jours','Après une heure','Jamais'],0]]},
 {id:'l12',minDay:22,title:'Formation au travail',script:'Notre nouvelle formation commencera mardi prochain à neuf heures. Elle durera toute la matinée. Merci d’apporter votre ordinateur portable. Le déjeuner sera offert par l’entreprise à midi trente.',qs:[['Quand commence la formation ?',['Mardi à 9 h','Lundi à midi','Vendredi à 18 h'],0],['Que faut-il apporter ?',['Un ordinateur portable','Un repas','Un vélo'],0],['Qui offre le déjeuner ?',['L’entreprise','Les participants','La mairie'],0]]},
 {id:'l13',minDay:28,title:'Atelier de réparation',script:'Samedi, le centre social organise un atelier pour apprendre à réparer les petits appareils électriques. L’activité est gratuite mais l’inscription est obligatoire car il n’y a que quinze places.',qs:[['Quand a lieu l’atelier ?',['Samedi','Lundi','Mercredi'],0],['Combien coûte-t-il ?',['Il est gratuit','15 euros','50 euros'],0],['Pourquoi faut-il s’inscrire ?',['Les places sont limitées','Il faut acheter un appareil','Le centre est fermé'],0]]},
 {id:'l14',minDay:33,title:'Journal local · cantines',script:'À partir de septembre, les cantines de la ville proposeront deux menus végétariens par semaine. La mairie affirme que les premiers tests ont été bien acceptés par les élèves. Une réunion avec les parents est prévue jeudi soir.',qs:[['Combien de menus végétariens par semaine ?',['Deux','Un par mois','Tous les jours'],0],['Comment les élèves ont-ils réagi aux tests ?',['Plutôt bien','Très mal','Ils ont refusé de manger'],0],['Quand a lieu la réunion ?',['Jeudi soir','Lundi matin','Samedi midi'],0]]},
 {id:'l15',minDay:38,title:'Chronique · déconnexion',script:'Une enquête montre que de nombreux salariés consultent encore leurs messages professionnels après leur journée. Les spécialistes conseillent de couper les notifications le soir et de définir avec l’équipe ce qui constitue une véritable urgence.',qs:[['Que font encore de nombreux salariés ?',['Ils consultent leurs messages après le travail','Ils changent de métier chaque soir','Ils suppriment Internet'],0],['Quel conseil est donné ?',['Couper les notifications le soir','Répondre immédiatement à tout','Dormir au bureau'],0],['Que faut-il définir avec l’équipe ?',['Ce qui est vraiment urgent','Le menu du déjeuner','La météo'],0]]}
);
V13_SPEAKING.push({id:'s0',minDay:1,part:'Fondation',title:'Mon quartier',prompt:'Décrivez votre quartier pendant environ une minute : où il se trouve, ce qu’il y a, ce que vous aimez et une chose que vous n’aimez pas.',target:75,check:['il y a','adjectifs','opinion simple','au moins 4 phrases']});
