const WRITINGS=[
 {title:'Courriel de réclamation',min:160,prompt:'Vous avez loué un appartement de vacances, mais plusieurs équipements ne fonctionnent pas. Écrivez au propriétaire : décrivez les problèmes, expliquez leurs conséquences et demandez une solution.',check:['type de texte adapté','faits/problèmes décrits','conséquences expliquées','demande claire','connecteurs','≥160 mots']},
 {title:'Opinion · transports publics',min:160,prompt:'Faut-il rendre les transports publics moins chers ? Donnez votre opinion, deux arguments et au moins un exemple précis.',check:['opinion claire','deux arguments','exemple précis','opposition/nuance','conclusion','≥160 mots']},
 {title:'Article · télétravail',min:160,prompt:'Un site demande aux lecteurs : « Le télétravail améliore-t-il la vie quotidienne ? » Écrivez un court article avec votre expérience ou des exemples, des avantages, des limites et votre opinion.',check:['contexte introduit','avantages','limites','exemple','opinion','≥160 mots']},
 {title:'Courriel · projet associatif',min:160,prompt:'Votre association souhaite organiser une activité pour le quartier. Écrivez aux membres pour présenter votre idée, expliquer son intérêt, proposer une organisation et demander leur avis.',check:['projet présenté','intérêt expliqué','organisation proposée','demande d’avis','registre adapté','≥160 mots']}
];
const SPEAKING=[
 {part:'Entretien dirigé',title:'Se présenter',prompt:'Parlez 2 à 3 minutes de vous : études ou travail, famille, loisirs, habitudes, une expérience passée et vos projets.',target:150,check:['présent','passé','projet futur','réponses développées']},
 {part:'Interaction',title:'Hôtel',prompt:'Votre chambre est trop bruyante. Expliquez le problème, réagissez aux propositions du réceptionniste et essayez d’obtenir une solution.',target:180,check:['politesse','problème clair','proposition','insistance/justification']},
 {part:'Interaction',title:'Remboursement',prompt:'Vous avez acheté un produit qui ne fonctionne pas. Le vendeur propose un échange, mais vous souhaitez un remboursement. Expliquez et négociez.',target:180,check:['expliquer','refuser poliment','insister','proposer une solution']},
 {part:'Point de vue',title:'Réseaux sociaux',prompt:'Les réseaux sociaux sont-ils plutôt utiles ou dangereux pour les jeunes ? Préparez puis parlez environ 3 minutes : thème, opinion, deux arguments, exemple, conclusion.',target:180,check:['thème','opinion','2 arguments','exemple','conclusion']},
 {part:'Point de vue',title:'Téléphone à l’école',prompt:'Faut-il limiter l’utilisation du téléphone à l’école ? Présentez votre opinion avec deux arguments, un contre-argument ou une nuance et une conclusion.',target:180,check:['opinion','arguments','nuance','exemple','conclusion']}
];
const DAYS=[
 ['基础诊断与句子骨架','Présent + 基础句型','se présenter','identité','建立可用的主谓宾和高频动词'],
 ['描述与提问','Articles + adjectifs + questions','décrire / demander','ville & personne','从单句扩展到描述和提问'],
 ['否定与礼貌请求','Négation + pouvoir/vouloir','demander / refuser','service','能表达“不要、不能、想要”'],
 ['时间与地点','Prépositions + 时间表达','situer / organiser','routine & transport','能说明时间、地点、频率'],
 ['过去事件 I','Passé composé','raconter une action','week-end','能讲昨天/周末发生了什么'],
 ['过去事件 II','Passé composé avec être','raconter un déplacement','voyage','能讲移动、到达与经历'],
 ['过去背景','Imparfait','décrire le passé','enfance','能描述过去习惯和背景'],
 ['叙事核心','PC vs imparfait','raconter une expérience','incident','把背景与事件组合起来'],
 ['计划与未来','Futur proche + futur simple','parler de projets','études & travail','能谈近期计划与未来预测'],
 ['基础复盘 I','D1–D9 混合复习','se présenter + raconter','identité','第一次闭环复测，减少新知识'],
 ['代词 I','COD / COI','éviter les répétitions','relations','提高句子自然度'],
 ['代词 II','Y / En','parler de lieux/quantités','ville & alimentation','掌握高频替代结构'],
 ['连接句子','Qui / que / où','décrire plus précisément','culture','从短句进入复合句'],
 ['比较','Comparatif','comparer / choisir','transport & logement','能比较两个方案'],
 ['礼貌与建议','Conditionnel','conseiller / demander','service & santé','为互动题建立礼貌表达'],
 ['逻辑关系 I','Cause / conséquence','expliquer','environnement','能解释原因和后果'],
 ['逻辑关系 II','Opposition + exemple','nuancer / illustrer','technologie','能加入转折和例子'],
 ['基础检查点','D1–D17 综合','mini-tâches','quotidien','目标：语法知识开始进入主动调用'],
 ['应用迁移 I','过去时复用','raconter une expérience','voyage','语法 → 1分钟叙事 → 短写作'],
 ['应用迁移 II','请求结构复用','demander / négocier','hôtel','语法 → 情景互动'],
 ['应用迁移 III','Conditionnel','conseiller / proposer','santé','提出建议并说明理由'],
 ['应用迁移 IV','Négation + politesse','se plaindre','logement','投诉但保持合适语气'],
 ['叙事组织','过去时 + connecteurs','organiser un récit','expérience','建立开头—经过—结果'],
 ['比较方案','Comparatif + opposition','avantages/inconvénients','transport','训练选择与权衡'],
 ['观点 I','Opinion + cause','donner son avis','école','观点 + 理由'],
 ['观点 II','Opinion + exemple + nuance','argumenter','technologie','观点 + 例子 + 转折'],
 ['书面应用 I','courriel','écrire un message','études','情境、对象、目的明确'],
 ['阅读应用','repérage','chercher une information','service public','扫读与定位'],
 ['听力应用','mots-clés + nombres','comprendre l’essentiel','annonce','主旨、数字、行动指令'],
 ['应用检查点','D19–D29 综合','enchaîner les fonctions','quotidien','目标：能完成多步骤真实任务'],
 ['DELF 听力 I','复习为主','idée générale','vie quotidienne','按考试方式做主旨与场景识别'],
 ['DELF 听力 II','复习为主','détails / nombres','travail','训练细节、数字、观点'],
 ['DELF 阅读 I','复习为主','informations utiles','annonce & service','针对任务定位信息'],
 ['DELF 阅读 II','复习为主','opinion / nuance','société','分析观点、理由与细节'],
 ['DELF 写作 I','connecteurs + temps','courriel/lettre','réclamation','45分钟内组织≥160词'],
 ['DELF 写作 II','argumentation','opinion écrite','société','观点、理由、例子、结论'],
 ['DELF 口语 I','时态综合','entretien dirigé','identité','2–3分钟谈过去、现在、未来'],
 ['DELF 口语 II','礼貌 + conditionnel','interaction','service','3–4分钟解决现实问题'],
 ['DELF 口语 III','argumentation','point de vue','médias','约3分钟连续观点表达'],
 ['Mini-mock 1','综合复习','4 compétences','mixte','第一次按时限组合训练'],
 ['Mock 1 + 复盘','错题优先','simulation','mixte','完整模拟 + 错因分类'],
 ['修复日 I','高频错误','remédiation','personnalisé','只攻击最弱语法和任务'],
 ['Mock 2','综合','simulation partielle','mixte','计时训练并比较稳定性'],
 ['修复日 II','听读错误','remédiation réception','mixte','主旨/细节/定位专项'],
 ['Mock 3','综合','simulation','mixte','再次检验是否稳定'],
 ['输出强化','写作 + 口语结构','production','société','输出速度和结构稳定性'],
 ['Mock 4','综合','simulation','mixte','接近考试节奏'],
 ['最终错题回炉','错误地图','remédiation','personnalisé','避免重复犯同一错误'],
 ['Final mock','综合','simulation finale','mixte','最后一次完整检测'],
 ['考试前稳定','不引入新语法','révision légère','mixte','结构、词块、策略和轻量输入']
];