const APPLICATION=[
 {topic:'Hôtel',title:'房间太吵',task:'Expliquez le problème et demandez poliment une autre chambre.',keys:['problème','voudrais','pourriez'],chunks:['Le problème, c’est que…','Je voudrais…','Pourriez-vous… ?']},
 {topic:'Restaurant',title:'电话订位',task:'Réservez une table pour quatre personnes samedi soir et précisez une contrainte alimentaire.',keys:['réserver','quatre','samedi'],chunks:['Je voudrais réserver…','Est-ce que vous avez… ?']},
 {topic:'Voyage',title:'火车取消',task:'Votre train est annulé. Demandez une autre solution au guichet.',keys:['train','annul','solution'],chunks:['Mon train a été annulé.','Quelle solution pouvez-vous proposer ?']},
 {topic:'Santé',title:'预约医生',task:'Expliquez un problème de santé et demandez un rendez-vous.',keys:['rendez-vous','depuis','mal'],chunks:['J’ai mal à… depuis…','Je voudrais prendre rendez-vous.']},
 {topic:'Logement',title:'邻居噪音',task:'Expliquez poliment le problème à votre voisin et proposez une solution.',keys:['bruit','soir','pourriez'],chunks:['Je voulais vous parler de…','Pourriez-vous… ?']},
 {topic:'Travail',title:'调整工作时间',task:'Demandez à commencer plus tôt pendant une semaine et justifiez votre demande.',keys:['semaine','parce','propose'],chunks:['Je souhaiterais…','C’est parce que…','Je vous propose de…']},
 {topic:'Études',title:'缺课补课',task:'Écrivez au professeur : expliquez votre absence et demandez comment rattraper le cours.',keys:['cours','rattrap','pourriez'],chunks:['Je ne pourrai pas assister…','Pourriez-vous m’indiquer… ?']},
 {topic:'Consommation',title:'商品退款',task:'Un produit ne fonctionne pas. Expliquez la situation et insistez pour obtenir une solution.',keys:['fonctionne','rembours','solution'],chunks:['Le produit ne fonctionne plus.','Je souhaiterais être remboursé.']},
 {topic:'Loisirs',title:'说服朋友出行',task:'Votre ami hésite à partir en week-end. Essayez de le convaincre avec deux arguments.',keys:['week-end','parce','pourrait'],chunks:['On pourrait…','Ce serait une bonne idée parce que…']},
 {topic:'Opinion',title:'学校里的手机',task:'Donnez votre opinion : faut-il limiter le téléphone à l’école ? Deux raisons + un exemple.',keys:['avis','parce','exemple'],chunks:['À mon avis,…','D’abord,…','Par exemple,…']}
];
const READINGS=[
 {title:'Médiathèque',text:'La médiathèque change ses horaires à partir du 1er septembre. Elle ouvrira à 9 h du mardi au samedi. Le mercredi, elle restera ouverte jusqu’à 21 h pour permettre aux étudiants de travailler plus longtemps. Le samedi, elle fermera à 17 h. Les usagers peuvent aussi réserver des documents en ligne et les récupérer à l’accueil.',qs:[['Quel jour peut-on rester jusqu’à 21 h ?',['Mercredi','Vendredi','Samedi'],0],['Que peut-on faire en ligne ?',['Réserver des documents','Passer un examen','Changer les horaires'],0],['Pourquoi la médiathèque ferme-t-elle plus tard le mercredi ?',['Pour les étudiants','Pour les touristes','Pour les employés'],0]]},
 {title:'Semaine de quatre jours',text:'Une entreprise de Nantes teste la semaine de quatre jours sans réduire les salaires. Les salariés travaillent plus longtemps du lundi au jeudi et ont leur vendredi libre. Plusieurs disent être moins stressés, même si certains trouvent les journées plus fatigantes.',qs:[['Quel avantage est cité ?',['Moins de stress','Plus de salaire','Moins de travail chaque jour'],0],['Quelle nuance apparaît ?',['Les journées sont parfois plus fatigantes','Le vendredi est travaillé','Les salaires baissent'],0],['Quel élément ne change pas ?',['Le salaire','Le nombre de jours libres','La durée de chaque journée'],0]]},
 {title:'Transport partagé',text:'Dans plusieurs villes françaises, les services de vélo partagé attirent de nouveaux utilisateurs. Ils apprécient surtout la liberté de prendre un vélo pour un trajet court sans devoir en acheter un. Cependant, certains usagers regrettent le manque de vélos disponibles le matin près des gares.',qs:[['Quel avantage est mentionné ?',['Pas besoin d’acheter un vélo','Les vélos sont gratuits','Les trajets sont toujours longs'],0],['Quel problème est cité ?',['Le manque de vélos le matin','Le prix du train','La fermeture des gares'],0],['Où le problème apparaît-il surtout ?',['Près des gares','Dans les écoles','Dans les restaurants'],0]]},
 {title:'Télétravail',text:'Depuis deux ans, une petite entreprise autorise ses employés à télétravailler deux jours par semaine. La direction constate que la plupart sont satisfaits et gagnent du temps sur les transports. Elle demande cependant aux équipes de venir au bureau les mêmes jours afin de conserver des moments de collaboration.',qs:[['Combien de jours peut-on télétravailler ?',['Deux','Trois','Cinq'],0],['Quel bénéfice est cité ?',['Gagner du temps de transport','Travailler moins','Être payé davantage'],0],['Pourquoi venir au bureau les mêmes jours ?',['Pour collaborer','Pour déjeuner','Pour voyager'],0]]}
];
const LISTENINGS=[
 {title:'Annonce de gare',script:'Attention s’il vous plaît. Le train à destination de Lyon, prévu à dix-sept heures vingt, partira finalement de la voie huit avec quinze minutes de retard. Les voyageurs sont invités à vérifier les écrans d’information.',qs:[['Quelle est la destination ?',['Lyon','Lille','Tours'],0],['De quelle voie part le train ?',['8','18','5'],0],['Quel est le retard ?',['15 minutes','50 minutes','5 minutes'],0]]},
 {title:'Message professionnel',script:'Bonjour Madame Martin. Je vous appelle au sujet de notre rendez-vous de jeudi. Je dois malheureusement le déplacer. Seriez-vous disponible vendredi matin vers dix heures ? Vous pouvez me rappeler avant dix-huit heures.',qs:[['Quel rendez-vous change ?',['Celui de jeudi','Celui de lundi','Celui de samedi'],0],['Quel nouveau moment est proposé ?',['Vendredi vers 10 h','Jeudi vers 18 h','Vendredi vers 18 h'],0],['Que doit faire Madame Martin ?',['Rappeler','Envoyer un colis','Annuler définitivement'],0]]},
 {title:'Radio locale',script:'La mairie vient d’annoncer l’ouverture d’un nouveau marché le dimanche matin. Les habitants pourront y acheter des produits locaux, notamment des légumes, du fromage et du pain. La circulation sera interdite dans la rue principale entre sept heures et quatorze heures.',qs:[['Quand ouvre le marché ?',['Dimanche matin','Samedi soir','Lundi matin'],0],['Que vendra-t-on ?',['Des produits locaux','Des voitures','Des billets de train'],0],['Jusqu’à quelle heure la rue est-elle fermée ?',['14 h','7 h','20 h'],0]]},
 {title:'Conseil de santé',script:'Pour mieux dormir, les spécialistes recommandent de réduire les écrans avant le coucher, de garder des horaires réguliers et d’éviter le café en fin de journée. Ils rappellent aussi qu’une activité physique régulière peut améliorer la qualité du sommeil.',qs:[['Que faut-il réduire avant de dormir ?',['Les écrans','L’eau','Les livres'],0],['Quand faut-il éviter le café ?',['En fin de journée','Le matin','À midi uniquement'],0],['Quelle activité peut aider ?',['L’activité physique','Regarder la télévision','Dormir toute la journée'],0]]}
];